# Generated by Django 3.0 on 2021-09-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210926_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
