# Generated by Django 3.0 on 2021-09-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210926_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_image_url',
        ),
    ]
